CREATE TABLE actas (
    id                      SERIAL,
    departamento            VARCHAR,
    provincia               VARCHAR,
    distrito                VARCHAR,
    nombre_local            VARCHAR,
    mesa                    VARCHAR,
    codigo_departamento     VARCHAR,
    codigo_provincia        VARCHAR,
    codigo_distrito         VARCHAR,
    codigo_local            VARCHAR,
    url_local               VARCHAR,
    url_mesa                VARCHAR,
    acta_numero_copia       VARCHAR,
    direccion               VARCHAR,
    acta_url                VARCHAR,
    num_electores           INTEGER,
    total_votantes          INTEGER,
    estado_del_acta         VARCHAR,
    votos_pl                INTEGER,
    votos_fp                INTEGER,
    votos_validos           INTEGER,
    votos_en_blanco         INTEGER,
    votos_nulos             INTEGER,
    votos_impugnados        INTEGER,
    votos_emitidos          INTEGER,
    last_updated            timestamp with time zone default current_timestamp,
    skip_reason             VARCHAR
);